### Data Cleaning

In [67]:
import pandas as pd

In [68]:
df = pd.read_csv('../data/raw/telco_churn.csv')

In [69]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [70]:
df.drop(columns='customerID',inplace=True)

In [71]:
df['Churn_Flag'] = df['Churn'].map({'Yes':1,'No':0})

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
 20  Churn_Flag        7043 non-null   int64
dtypes: float64(1), int64(3), object(17)
memory usage: 1.1+ MB

In [73]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
Churn_Flag          0
dtype: int64

In [74]:
df['TotalCharges'].dtype

dtype('O')

In [75]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors='coerce')
df['TotalCharges'].isna().sum()

11

In [76]:
df['TotalCharges'].fillna(df['TotalCharges'].median(),inplace=True)

/var/folders/m9/rns_73l10vl4v8dj6j2vt6mm0000gn/T/ipykernel_70707/3929950690.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(df['TotalCharges'].median(),inplace=True)

In [77]:
for col in df.columns:
    print(col, df[col].unique())

gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
PhoneService ['No' 'Yes']
MultipleLines ['No phone service' 'No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes' 'No internet service']
OnlineBackup ['Yes' 'No' 'No internet service']
DeviceProtection ['No' 'Yes' 'No internet service']
TechSupport ['No' 'Yes' 'No internet service']
StreamingTV ['No' 'Yes' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn ['No' 'Yes']
Churn_Flag [0 1]

In [78]:
binary_cols = ['Partner','Dependents','PhoneService','OnlineSecurity','PaperlessBilling',
               'OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies']
for col in binary_cols:
    df[col] = df[col].map({'Yes':1,'No':0})

In [79]:
df['gender'] = df['gender'].map({'Male':0,'Female':1})

In [83]:
multi_cols = ['MultipleLines','InternetService','Contract','PaymentMethod']
df = pd.get_dummies(df, columns=multi_cols, drop_first=True)

In [84]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,Churn_Flag,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,1,0,0.0,1.0,0.0,0.0,...,0,True,False,False,False,False,False,False,True,False
1,0,0,0,0,34,1,1.0,0.0,1.0,0.0,...,0,False,False,False,False,True,False,False,False,True
2,0,0,0,0,2,1,1.0,1.0,0.0,0.0,...,1,False,False,False,False,False,False,False,False,True
3,0,0,0,0,45,0,1.0,0.0,1.0,1.0,...,0,True,False,False,False,True,False,False,False,False
4,1,0,0,0,2,1,0.0,0.0,0.0,0.0,...,1,False,False,True,False,False,False,False,True,False

In [95]:
print(df.select_dtypes(include='object').columns)
print('Total missing values:',df.isna().sum().sum())

Index(['Churn'], dtype='object')
Total missing values: 9156

In [96]:
df.fillna(0, inplace=True)

In [97]:
print('Total missing values:',df.isna().sum().sum())

Total missing values: 0

In [98]:
df.drop(columns=['Churn'], inplace=True)

### Scaling Data

In [103]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

num_cols = ['tenure','MonthlyCharges','TotalCharges']
df[num_cols] = scaler.fit_transform(df[num_cols])

In [106]:
import joblib
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']